### PR TITLE
add cmake to build matrix

### PR DESCRIPTION
**Pull request by reqshark**
run a cmake build on each OS during integration test

### CODE REVIEW

**Comment by procedural** [comment]
Looking at Travis build fail for Linux:

```
[ 59%] Building C object CMakeFiles/perf_chan.dir/perf/chan.c.o
Linking C executable perf/chan
libmill.a(utils.c.o): In function `now':
utils.c:(.text+0x46): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[2]: *** [perf/chan] Error 1
make[1]: *** [CMakeFiles/perf_chan.dir/all] Error 2
make: *** [all] Error 2
```

I didn't had this issue on my setup.

**Comment by procedural** [comment]
>Add -lrt to the end of g++ command line. This links in the librt.so "Real Time" shared library.

http://stackoverflow.com/a/2418175

**Comment by reqshark** [comment]
@procedural I'll try that, but i also think we might need to update the travis version off gcc

**Comment by procedural** [comment]
>we might need to update the travis version off gcc

Yea, most likely

**Comment by reqshark** [comment]
yep, linking librt fixed the cmake build for that box

**Comment by procedural** [comment]
Oh, one note, when you set `CMAKE_REQUIRED_LIBRARIES` [here](https://github.com/sustrik/libmill/pull/105/files#diff-af3b638bc2a3e6c650974192a53c7291R16) you should also reset it to empty list [like I did in this PR](https://github.com/sustrik/libmill/pull/106) to fix other checks which don't depend on this library.

**Comment by sustrik** [comment]
procedural: Submitted under MIT license?

Alternatively, if you want to contribute in the future, you can say "All my future patches, unless stated otherwise, will be submitted under MIT license," and be done with it once and for all.

**Comment by procedural** [comment]
@sustrik All my future patches, unless stated otherwise, will be submitted under WTFPL license

**Comment by reqshark** [comment]
@procedural how is that? 

while WTFPL license is my personal preference, all my future patches, unless stated otherwise, will be submitted under MIT license.

**Comment by procedural** [comment]
@reqshark you can remove these two lines:

```
add_definitions(-DHAVE_LIBRT)
```

and 

```
set(CMAKE_REQUIRED_DEFINITIONS )
```

Since `HAVE_LIBRT` definition is not used anywhere and you didn't set `CMAKE_REQUIRED_DEFINITIONS` anyway :)

**Comment by sustrik** [comment]
procedural@: WTFPL seems compatible with MIT/X11 but I am not a lawyer, so it's hard to say. There is a clause about not changing the license in at least one version of WTFPL, which may possibly cause trouble.

Please, take into account that clear licensing is needed for any software to pass corporate legal review process.

**Comment by procedural** [comment]
@sustrik ok, then:

All my future patches, unless stated otherwise, will be submitted under MIT license.

Real question: isn't when MIT project accepts someone's PR code it automatically becomes MIT too?

**Comment by procedural** [comment]
@reqshark :+1:

**Comment by sustrik** [comment]
Nope, that only works for  GPL/LGPL as it has the concept of "derivative work" implicitly inheriting the license. No such thing in MIT/X11.

**Comment by procedural** [comment]
@sustrik that's scary. What if someone will lie to you and you'll accept their patch that was taken from GPL library?

**Comment by sustrik** [comment]
The problem applies to any permissively licensed project. You would be probably asked to remove the patch once the violation is discovered.

**Comment by procedural** [comment]
I contributed to many OS projects, MIT / BSD, they accepted pull requests with no questions, yours is the first one which asked me this :) Is this because of restrict copyright laws of your country or some other reasons?

**Comment by procedural** [comment]
For example, no one gives a shit about licenses here in Russia. I bet you if you go to Kremlin they have pirated Windows installed on their machines. Not that they greed, they just don't care.

**Comment by sustrik** [comment]
It's just to be on the safe side. With all the bullshit licensing lawsuits in US you just want to.

**Comment by reqshark** [comment]
I think it was made MIT so that libmill could be used in a corporate setting without lawyers and politics to get in the way. Any time there is money involved u will find politics nearby. I don't care what country it is, politics still has the potential to hurt developers trying to do the right thing.

**Comment by procedural** [comment]
>I don't care what country it is, politics still has the potential to hurt developers trying to do the right thing.

This is true. Sorry for off topic, by the way!

@reqshark this PR is ready to be merged?

**Comment by reqshark** [comment]
@procedural i think if you want to give this PR the :+1: then it should be merged. @sustrik would you like me to rebase and squash into one commit?

**Comment by sustrik** [comment]
No need. I merged it as is. Thanks!

**Comment by procedural** [comment]
@reqshark @sustrik thanks, guys!

**Comment by reqshark** [comment]
wait, why did test 6, `test_go` on osx with cmake do a segfault just now?

i ran it several times on osx without this

**Comment by reqshark** [comment]
@sustrik can you add a dummy commit to master to see if the build is actually failing?

**Pull request merged**
