### PR TITLE
Removed unnecessary if and goto statement.

### PR DESCRIPTION
**Pull request by aditya3098**

### CODE REVIEW

**Comment by sustrik** [comment]
These lines are actually needed. tcpflush() sets errno to 0 in case of success or to error code in case of failure.

**Comment by reqshark** [comment]
well @aditya3098 might have been onto something, why not move all the `if(errno != 0)`s down under the cleanup label so the check happens on the line before `tcpclose(as);`?

**Comment by reqshark** [comment]
oh nevermind that would defeat the purpose of the lines in between :)

**Comment by nirs** [comment]
Checking errno does not change the flow, so the next line is always the cleanup. Maybe I'm missing something?

**Comment by sustrik** [comment]
Ah, I haven't noticed that it's removed only when it's the last operation.

Anyway, I would prefer it to stay in place for its eduactional value, i.e. that errno should be checked after calling tcpflush().

Also, it's safer for people copy-pasting from the tutorial.

**Comment by aditya3098** [comment]
I guess from an educational POV it makes sense. However, might it be better
to leave a comment with an explanation? I think most optimising compilers
would ommit that anyway.

**Comment by sustrik** [comment]
I've added comment about it into the tutorial.

**Pull request closed without merging**
