### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by nickdesaulniers**
an additional build system, using cmake.  Should help folks build this on Windows (not like I have a Windows machine to test on).  Using this, folks can build Makefiles, XCode project files, or VS project files.  I build like:

```
cd libmill
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```

folks can do `cmake -G Xcode ..` or `-G 'Visual Studio 14 2015 Win64'`

### CODE REVIEW

**Comment by sustrik** [comment]
Nice! Can you please state the patch is submitted under MIT license?

**Comment by nickdesaulniers** [comment]
The 2 submitted patches and all subsequent patches I submit to this project are licensed under the current license of this project; which at this time is the MIT license.

**Comment by nickdesaulniers** [comment]
oh, I forgot to build the stuff in perf.  Want me to add it here or in a follow up PR?

**Comment by nickdesaulniers** [comment]
oops, also am not yet building a shared lib (was only building a static lib)

**Comment by nickdesaulniers** [comment]
ok, I think this is good to go.  One thing I didn't check is that for the perf stuff I'm linking to the static lib, not the shared lib, so this might have performance implications (read improvements) if with the old build system you're linking against the shared lib.

Also, I think there's a way of generating a test harness similar to `make check` but I'll have to research that.

Finally, we should update the docs that you can also use cmake to build.

**Comment by sustrik** [comment]
Thanks! If you want to improve the CMake build, one important thing is to use -O1 when building with clang. There's some kind of compiler bug there which makes it fail with -O2.

**Comment by nickdesaulniers** [comment]
I was looking at the bug you have on file for that, #21 .  I cannot reproduce.  I'll post in there.

Note: with cmake, usually you either run `cmake ..` which generates a Makefile with optimizations off (you can check this with `VERBOSE=1 make`) or `cmake -DCMAKE_BUILD_TYPE=Release ..` which has -O3.

**Pull request merged**
