### PR TITLE
Disable coredumps in expected to crash test processes

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by sustrik** [comment]
I think nirs@ is right. Is there any hurt in keeping coredumps around?

**Comment by ebfe** [comment]
Well I can't really follow how this makes debugging child processes much harder.
First note that the children are 5 lines long and the code in these lines is
covered in the tests before already. Second there is no effort made to
distinguish why the child aborts, so there is no way to check if you hit the
assert we are testing or an unrelated one. If you want to investigate a test
failure, note that in that case there is no coredump for the interesting child
process.

In what case would a child process coredump actually be useful?

> What if we set a signal handler so alarm() will cause the child process to
> exit with specific error code?

Hmm, I don't see how this would get rid of the coredumps in the case of a
successfull test.

>  Is there any hurt in keeping coredumps around?
I think they are annoying, confusing and due to the way the tests are set up
provide no real value.

Either way feel free to close this if they don't bother you.

**Comment by jimjag** [comment]
Could we have some sort of env-var which specifies whether or not to
core-dump?

**Comment by sustrik** [comment]
I don't feel strongly either way, however, is there any advantage in *not* having coredumps?

**Comment by ebfe** [comment]
On Sun, Sep 13, 2015 at 07:18:38AM -0700, sustrik wrote:
> I don't feel strongly either way, however, is there any advantage in *not* having coredumps?

It's really just an annoyance. Having either to constantly delete
coredumps from successful test runs/digging for the one that actually
failed.

**Comment by nirs** [comment]
On OS X you get an annoying popup each time some process dumps core, and your crash reports logs are spammed  with these unhelpful fake crash report created by successful tests. I agree with efbe that we should not create fake core dumps.

I'll send a patch using signal handler, I believe it will be more useful in the long term.

**Comment by sustrik** [comment]
Ok, understood.

**Comment by nirs** [comment]
Here is a version that does the same thing with a signal handler:
https://github.com/sustrik/libmill/pull/112

**Pull request closed without merging**
