### PR TITLE
Fix int declaration inside of for loop

### LINKED ISSUE #101: 0.18-rc: "‘for’ loop initial declarations are only allowed in C99 or C11 mode" compile time error
```
/home/constantine/Desktop/libmill/tests/signals.c:71:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for(int i = 0; i < COUNT; ++i) {
     ^
/home/constantine/Desktop/libmill/tests/signals.c:71:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```

Makefile was generated from CMake.

### PR DESCRIPTION
**Pull request by procedural**
Fixes #101

### CODE REVIEW

**Comment by sustrik** [comment]
merged. Thanks!

**Comment by procedural** [comment]
@sustrik thank you!

**Comment by reqshark** [comment]
@procedural that fixed the cmake build for me on osx just now. thanks!

**Comment by procedural** [comment]
@reqshark cool! I tested it with CMake too, it works under Linux now too.

**Pull request merged**
