### PR TITLE
remove unused includes

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
we should also take a look at the use of assert throughout the code base, since configuring with `cmake -DCMAKE_BUILD_TYPE=Release ..` for optimized builds will use the `-NDEBUG` flag which will remove the expressions within assert statements entirely.  That, or possibly force cmake to not build with that flag for the tests at least.

**Comment by sustrik** [comment]
Please, keep the asserts in place. They are cheap and guarantee that the program will fail rather that exhibit weird behaviour if there is a bug.

**Comment by nickdesaulniers** [comment]
sure, maybe move that comment over to bug #34 ? This PR simply removes unused includes.

**Comment by sustrik** [comment]
Merged. Thanks!

**Pull request merged**
