### PR TITLE
Extract find_pollset helper

### PR DESCRIPTION
**Pull request by nirs**
Replace duplicate pollset search loop with a helper without changing the
semantics.

Submitted under MIT/X11 license
Signed-off-by: Nir Soffer <nsoffer@redhat.com>

### CODE REVIEW

**Comment by sustrik** [comment]
Please, rename it to mill_find_pollset(). Thanks!

**Comment by nirs** [comment]
Sure.

**Comment by nirs** [comment]
Renamed.

**Comment by sustrik** [comment]
Merged. Thanks!

**Pull request merged**
