### PR TITLE
adjust clock precision at runtime

### PR DESCRIPTION
**Pull request by XiaoxiaoPu**
It runs well on my laptop. The clock precision is about 2100000 on 2.2 GHz Intel Core i7. I don't know if it's necessary, please think it over. :)

### CODE REVIEW

**Comment by sustrik** [comment]
The problem is that rdtsc tick interval changes depending on whether power-saving mode is no or not.

Thus, I think, we need a conservative estimate rather than precise estimate which will turn out inaccurate once the power saving kicks in.

**Comment by XiaoxiaoPu** [comment]
If the CPU frequency changes, the clock precision will be adjusted.

**Comment by sustrik** [comment]
What I meant was that you are sacrificing some precision at the point when power saving mode changes (e.g. msleep(1) can actually last 2 ms). Which may be a defendable position, but there needs to be a reason to do it in the first place. Have you tried to run some benchmarks to show the performance improvement, so that we can judge whether it's worth it?

**Comment by sustrik** [comment]
Ok, I've run a short test. Without the patch, one call to now() takes ~7.40ns. With the patch it's ~7.37ns.  To put in in context, in 0.03ns light will trave 9mm. I think the optimisation is not worth it.

**Comment by XiaoxiaoPu** [comment]
OK. Thans for your time.

**Pull request closed without merging**
