### PR TITLE
add travis ci

### PR DESCRIPTION
**Pull request by reqshark**
#35

### CODE REVIEW

**Comment by reqshark** [comment]
i added some travis ci configuration. 

it runs the test suite on every Pull Request and on every update or commit someone adds on the PR. 

Github shows the result: passing with a green check mark or failing with a red X next to commits.

The integration badge on the readme tracks master branch since we want to display the passing or failing status of master, not PRs or other random branches: 

[Build Status](https://travis-ci.org/reqshark/mill)

since it's configured to my fork temporarily it needs to be updated. @sustrik, you can login to [travis](https://travis-ci.org/) with your github credentials. You'll see a list of all your repos. Click the checkbox on libmill to activate the integration--it hooks into `.travis.yaml` and then we can update this [Build Status](https://travis-ci.org/reqshark/mill) badge to point back here. At that point the ci integration begins.

**Comment by sustrik** [comment]
Uh. No OSX for now. Which makes the whole exercise almost useless :( Anyway, I am merging the patch now and we'll wait whether OSX becomes available...

Thanks for the patch!

**Comment by reqshark** [comment]
sure, when they stop the ban on os x repos, I'll ping you. btw an all lowercase `readme.markdown` is probably quicker to type than the old fashioned way

**Comment by sustrik** [comment]
It's a matter of custom. Old-style hackers like me look for README, COPYING, AUTHORS and such.

**Comment by reqshark** [comment]
ya totally the `.md` is a big step :+1:

**Pull request merged**
