### PR TITLE
Fix ipremote memory leaks

### PR DESCRIPTION
**Pull request by antonmes**
Sorry, i could test only [this line](https://github.com/sustrik/libmill/compare/master...antonmes:master?expand=1#diff-9057a6065f48975860ca814ef25354e0R350), but the rest seems logical.
Also i'm not sure how to write a test for this leak.

[before / after](https://cloud.githubusercontent.com/assets/5857728/15154770/5e0b9a8a-16f0-11e6-9980-a7b595c1846f.png)

### CODE REVIEW

**Comment by antonmes** [comment]
Memory is allocated [here](https://github.com/sustrik/libmill/blob/master/dns/dns.c#L7457).

**Comment by sustrik** [comment]
Interesting. This looks like a memory leak in dns.c

AFAICT dns_ai_close() should deallocate everything that was allocated while doing the query.

It may be worth reporting this back to <william@25thandClement.com>

**Comment by sustrik** [comment]
No. You are actually right. It seems that entity returned by dns_ai_nextent() must be freed by hand afterwards.

**Comment by sustrik** [comment]
Can you state that you are submitting the patch under MIT/X11 license?

**Comment by antonmes** [comment]
yep, should i add an asterisk to the authors file?

**Comment by sustrik** [comment]
If you don't want to make such declaration for every future patch to the project, adding a star would make sense.

**Comment by antonmes** [comment]
done.

**Pull request merged**
