### PR TITLE
Remove DOIT to stop use of doitlibtool

### PR DESCRIPTION
**Pull request by jschimpf-pandora**
The doitlibtool script has been depreciated and removing the DOIT line in the configure.ac turns it off and uses libtool instead.  Works in OS X but more importantly works now in Yocto as a recipe to add the library to a new system

### CODE REVIEW

**Comment by sustrik** [comment]
Merged into mainline. Thanks!

**Comment by jschimpf-pandora** [comment]
Finally finally I got all my Yocto ducks in  a row and got your library and a C compiler on the BeagleBone image.  I had built a modified version of your tutorial program on OX X.  Cut and pasted that into a file on the BBB and it built and ran just like the original. 

Thanks for your help and if anyone wants it this is the recipe for libmill on yocto.

# -----------------------------------------------------
# Header Meta data
SUMMARY = "Co-routine & Network Library"
DESCRIPTION = "Easy network use and co-routine operation"
AUTHOR = "Martin Sustrik"
HOMEPAGE = "https://libmill.org"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://COPYING;md5=6d82245bd22227ca739abaf3dcd3b80d"
PR = "1.0"

# -----------------------------------------------------
# Source data
# My fork
SRCREV = "419f4eb0b9aa9298ccbf434f24464ec292469951"
SRC_URI = "git://github.com/sustrik/libmill.git;protocol=https"
inherit autotools gettext 

S = "${WORKDIR}/git"

Thanks again for a really nice tool.

—jim schimpf

**Comment by sustrik** [comment]
Nice!

Would it make sense to include the recipe in libmill package?

Martin

**Comment by jschimpf-pandora** [comment]
Not sure where to put it (Yocto_recipe directory ?) but libmill is made for the embedded world and Yocto makes it easy to get into a distribution. You are free to put it where you wish. 

Thanks for writing.

—jim_schimpf

**Pull request closed without merging**
