### PR TITLE
Check if stack guard and dns are supported and add them to CMake build

### LINKED ISSUE #94: cmake build broken
...
    [ 91%] Linking C executable tests/tcp
    libmill.a(ip.c.o): In function `ipremote':
    ip.c:(.text+0xc3f): undefined reference to `getaddrinfo_a'
    ip.c:(.text+0xd0b): undefined reference to `gai_cancel'
    ip.c:(.text+0xd88): undefined reference to `gai_error'
    collect2: error: ld returned 1 exit status
    CMakeFiles/test_tcp.dir/build.make:95: recipe for target 'tests/tcp' failed
    make[2]: *** [tests/tcp] Error 1
    CMakeFiles/Makefile2:696: recipe for target 'CMakeFiles/test_tcp.dir/all' failed
    make[1]: *** [CMakeFiles/test_tcp.dir/all] Error 2
    Makefile:94: recipe for target 'all' failed
    make: *** [all] Error 2

I guess `-lanl` is missing from the linker flags. Not sure where/how to add it.

### PR DESCRIPTION
**Pull request by procedural**
Fixes #94

### CODE REVIEW

**Comment by sustrik** [comment]
This is a non trivial patch. Can you state that it's submitted under MIT license? Thanks!

**Comment by procedural** [comment]
@sustrik of course it is!

**Comment by procedural** [comment]
>mprotect and posix_memalign are independent from getaddrinfo_a

Didn't know that. How can we check for them?

**Comment by procedural** [comment]
@ebfe Found it.

**Comment by sustrik** [comment]
Merged. Thanks!

**Comment by procedural** [comment]
I've tested it on Linux and it works for me, @ebfe would be great if you confirm it's working for you as well

**Comment by ebfe** [comment]
On Wed, Sep 09, 2015 at 02:36:45AM -0700, Constantine wrote:
> I've tested it on Linux and it works for me, @ebfe would be great if you confirm it's working for you as well

The mprotect/posix_memalign checks don't seem to work on FreeBSD.

**Comment by procedural** [comment]
@ebfe could you add these `message` lines to debug it?

```cmake
check_function_exists(mprotect HAVE_MPROTECT)
if(HAVE_MPROTECT)
  message("HAVE_MPROTECT is defined!")
  add_definitions(-DHAVE_MPROTECT)
endif()

check_function_exists(posix_memalign HAVE_POSIX_MEMALIGN)
if(HAVE_POSIX_MEMALIGN)
  message("HAVE_POSIX_MEMALIGN is defined!")
  add_definitions(-DHAVE_POSIX_MEMALIGN)
endif()
```

My output on Linux on project generation:

```
$ cmake ..
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for getaddrinfo_a
-- Looking for getaddrinfo_a - found
-- Looking for mprotect
-- Looking for mprotect - found
HAVE_MPROTECT is defined!
-- Looking for posix_memalign
-- Looking for posix_memalign - found
HAVE_POSIX_MEMALIGN is defined!
-- Configuring done
-- Generating done
-- Build files have been written to: /home/constantine/Desktop/libmill/build
```

**Comment by procedural** [comment]
Maybe we should move these checks at the top of CMakeLists.txt so that it defines them before `add_library` command?..

**Comment by ebfe** [comment]
```
$ cmake ..
-- The C compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for getaddrinfo_a
-- Looking for getaddrinfo_a - not found
-- Looking for mprotect
-- Looking for mprotect - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/mg/src/libmill/build
```

**Comment by procedural** [comment]
Maybe FreeBSD requires additional definitions / libraries for these commands?..

**Comment by procedural** [comment]
Oh, from your log:

```
-- Looking for getaddrinfo_a
-- Looking for getaddrinfo_a - not found
-- Looking for mprotect
-- Looking for mprotect - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
```

Sorry, it means CMake can't find them and thus your setup probably doesn't have them too... We should try to find it manually if we want to be sure.

**Comment by procedural** [comment]
@ebfe first, locate `netdb.h` on your system. On my machine it's path is `/usr/include/netdb.h`. Open it and try to search for `getaddrinfo_a` in it. Here it's in my file:

**Comment by ebfe** [comment]
My setup has mprotect and posix_memalign. They are correctly detected by the autoconf based build.

The problem is unconditionally adding libanl to CMAKE_REQUIRED_LIBRARIES as that breaks the check_function_exists check.

Dropping the `list(APPEND CMAKE_REQUIRED_LIBRARIES anl)` line makes the checks work:

```
$ cmake ..
-- The C compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for getaddrinfo_a
-- Looking for getaddrinfo_a - not found
-- Looking for mprotect
-- Looking for mprotect - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Configuring done
-- Generating done
```

but this breaks the getaddrinfo_a check under Linux.

**Comment by procedural** [comment]
>-- Looking for getaddrinfo_a - not found
`getaddrinfo_a` is still not found, try my steps above!

**Comment by procedural** [comment]
>My setup has mprotect and posix_memalign. They are correctly detected by the autoconf based build.

Then we should ifdef it for FreeBSD.

>The problem is unconditionally adding libanl to CMAKE_REQUIRED_LIBRARIES as that breaks the check_function_exists check.

Looks like a bug in CMake, is it known? Should we file it?

**Comment by sustrik** [comment]
A comment: getaddrinfo_a is a Linux-specific thing. It doesn't exist on FreeBSD or OSX.

**Comment by procedural** [comment]
@sustrik thanks! So we definitely should ifdef it. As of mprotect and posix_memalign checks, I see people on github do line like:

```
SET(CMAKE_REQUIRED_LIBRARIES )
```

Which, apparently, resets the requirement. Will PR fix right now...

**Comment by ebfe** [comment]
Yes, I know that getaddrinfo_a isn't available on FreeBSD. This isn't the issue. The issue is that adding libanl unconditionally to CMAKE_REQUIRED_LIBRARIES break the check_function_exists checks (since they now try to compile with -lanl), and thus break the mprotect/posix_memalign checks.

**Comment by procedural** [comment]
@ebfe got it! Fix on the way.

**Pull request merged**
